# Generated by Django 4.1.7 on 2023-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('likes', models.BigIntegerField()),
                ('dislikes', models.BigIntegerField()),
            ],
        ),
    ]
