# Generated by Django 4.1.7 on 2023-03-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('year_of_release', models.BigIntegerField()),
                ('no_of_songs', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('star_sign', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='To_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.album')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.singer')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.singer'),
        ),
    ]
